name: AniLib build artifact
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" &> /dev/null

      - name: Create gradle property file
        env:
          ANILIST_SECRET: ${{ secrets.ANILIST_SECRET }}
        run:
          echo "$ANILIST_SECRET" | base64 -d > ./secret.properties

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Set CURRENT_SHA
        run: |
          set -x
          echo "CURRENT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Upload apk
        uses: actions/upload-artifact@v2.2.0
        with:
          name: AniLib-${{env.CURRENT_SHA}}
          path: app/build/outputs/apk/debug/*.apk



