name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4.2.0
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.5.0

      - name: Set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 17
          distribution: adopt
          
      - name: Create gradle property file
        env:
          ANILIST_SECRET: ${{ secrets.ANILIST_SECRET }}
          $GOOGLE_SERVICES_JSON: ${{ secrets.$GOOGLE_SERVICES_JSON }}
          $DEBUG_KEYSTORE: ${{ secrets.$DEBUG_KEYSTORE }}
        run:
          echo "$ANILIST_SECRET" | base64 -d > ./secret.properties
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > ./app/src/debug/google-services.json
          # create common debug keystore
          mkdir -p ~/.android/ && echo "$DEBUG_KEYSTORE" | base64 --decode > ~/.android/debug.keystore

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/app-debug.apk
